server:
  port: 8090
error:
  include-message: always
  include-binding-errors: always
spring:
  cloud:
    compatibility-verifier:
      enabled: false
    gateway:
      routes:
        - id: cliente-service
          uri: http://cliente-service:8091
          predicates:
            - Path=/api/clientes/**
        - id: producto-service
          uri: http://producto-service:8092
          predicates:
            - Path=/api/productos/**
        - id: inventario-service
          uri: http://inventario-service:8093
          predicates:
            - Path=/api/inventarios/**
        - id: pedido-service
          uri: http://pedido-service:8094
          predicates:
            - Path=/api/pedidos/**
        - id: pago-service
          uri: http://pago-service:8095
          predicates:
            - Path=/api/pagos/**
        - id: autenticacion-service
          uri: http://autenticacion-service:8096
          predicates:
            - Path=/api/usuarios/**
        - id: auth-service
          uri: http://autenticacion-service:8096
          predicates:
          - Path=/api/auth/**
        - id: notificacion-service
          uri: http://notificacion-service:8097
          predicates:
            - Path=/api/notificaciones/**
        - id: auditoria-service
          uri: http://auditoria-service:8098
          predicates:
            - Path=/api/auditorias/**
        - id: reporte-service
          uri: http://reporte-service:8099
          predicates:
            - Path=/api/reportes/**
  application:
    name: api-gateway
