spring.application.name=pedido-service
server.port=8084

spring.datasource.url=jdbc:mysql://mysql:3306/db_pedido?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.liquibase.enabled=true
spring.jpa.hibernate.ddl-auto=validate
spring.liquibase.change-log=classpath:db/changelog/db.changelog.sql
spring.jpa.show-sql=true